name: 构建 Caddy Docker 镜像并上传 Docker HUB

on:
  # 当发布新的 release 时触发
  release:
    types: [published]
  # 手动触发工作流
  workflow_dispatch:
  # 定时触发，每周检查一次 Caddy 更新
  schedule:
    - cron: '0 0 * * 0'

env:
  DOCKER_IMAGE: juijote/caddy
  PLATFORMS: linux/amd64,linux/arm64,linux/arm/v7

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Get latest Caddy version
        id: caddy-version
        run: |
          LATEST_VERSION=$(curl -s "https://api.github.com/repos/caddyserver/caddy/releases/latest" | jq -r ".tag_name")
          echo "version=${LATEST_VERSION#v}" >> $GITHUB_OUTPUT

      - name: Generate Dockerfile
        run: |
          cat > Dockerfile << 'EOF'
          FROM caddy:builder AS builder

          RUN xcaddy build \
              --with github.com/caddy-dns/alidns \
              --with github.com/caddy-dns/cloudflare \
              --with github.com/caddy-dns/dnspod \
              --with github.com/greenpau/caddy-security \
              --with github.com/mholt/caddy-webdav \
              --with github.com/mholt/caddy-dynamicdns \
              --with github.com/mholt/caddy-ratelimit \
              --with github.com/corazawaf/coraza-caddy/v2 \
              --with github.com/dulli/caddy-wol \
              --with github.com/Wafris/wafris-caddy

          FROM caddy:latest
          COPY --from=builder /usr/bin/caddy /usr/bin/caddy
          EOF

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          platforms: ${{ env.PLATFORMS }}
          push: true
          tags: |
            ${{ env.DOCKER_IMAGE }}:github
            ${{ env.DOCKER_IMAGE }}:${{ steps.caddy-version.outputs.version }}
